### ISSUE TITLE
mlflow.exceptions.MlflowException: Run 'LIFFireNet' not found

### ISSUE THREAD

**Issue by ChidanandKumarKS** [tudelft/event_flow#1]
Kindly let us know how to solve this issue after running 
python eval_flow.py LIFFireNet --config configs/eval_ECD.yml
Kindly help

**Comment by Huizerd** [comment]
Hi! Have a look at [this](https://github.com/tudelft/event_flow#download-models) section of the readme; you should download the pretrained models before you can run an evaluation (or train your own models)

**Comment by ChidanandKumarKS** [comment]
Hi,

I put all the pretrained models in a current directory. But still the same issue with a bug

**Comment by Huizerd** [comment]
What does your directory structure look like? In order to make it work, `mlflow.zip` should be extracted inside `event_flow/`, such that it looks like this:
```
event_flow
|-- mlruns
    |-- 42
        |-- meta.yaml
        |-- LIFFireNet
        |   |-- ...
        |-- ALIFFireNet
        |   |-- ...
etc.
```

**Comment by ChidanandKumarKS** [comment]
Worked like a charm.  Thanks solved.
Also your paper is exceptional in self supervised paradigm

**Comment by Huizerd** [comment]
Good to hear! And thanks :) Good luck with experimenting!

**Comment by hbg180** [comment]
Hi, I'm having the same problem. After I unzip the `mlruns.zip` file, I get `_MACOSX` and `mlruns 2` folders. I move the `42` folder under the `mlruns 2` folder to the `mlruns` directory and delete the `_MACOSX` and `mlruns 2` folders. This way I get the same directory structure as you said. How should I resolve this error? Thanks!
