### ISSUE TITLE
Problem with "time" mode

### ISSUE THREAD

**Issue by AiladReb** [tudelft/event_flow#10]
Hello,

When using the 'time' mode, a problem arises in the code because each sample contains a different number of events. This variability in event count prevents the Collate_fn function from concatenating tensors due to mismatched dimensions, resulting in numerous errors in the Flow.py functions. 

Do you have a code version where the time mode is used ? 

Thank you

**Comment by Huizerd** [comment]
Unfortunately we didn't end up using time mode, so we didn't implement this in code. However, you could have a go at it, I would suggest looking at [`torch.nn.utils.rnn.pad_sequence`](https://pytorch.org/docs/stable/generated/torch.nn.utils.rnn.pad_sequence.html), with which you can pad sequences of uneven length to the same length.
