### ISSUE TITLE
dataset link and pretrain model link not available

### ISSUE THREAD

**Issue by AesthetiC631** [tudelft/event_flow#11]
Thanks for you great work！ 

While the link for datasets and pretrained model can not be opened.

Is there another link for that?

**Comment by Huizerd** [comment]
I just checked and both links work for me, not sure what the issue could be.

**Comment by AesthetiC631** [comment]
Thank you so much for your response！I have reviewed the data and model links again and I can confirm they are accessible and ok to use.It might be an issue with my network on this end. Thanks again!

**Comment by Huizerd** [comment]
no problem, and good luck!
