### ISSUE TITLE
"SpikingRecEVFlowNet" encoder and decoder framework for image reconstruction using event camera

### ISSUE THREAD

**Issue by ChidanandKumarKS** [tudelft/event_flow#2]
@Huizerd ,

I was using your module "SpikingRecEVFlowNet" as a a network to reconstruct images from event camera rather than optical flow and according modified the input and output channels compatible to image reconstruction. After making the environmental setup. I landed with bad image reconstruction results
![Custom_SNN](https://user-images.githubusercontent.com/25030434/154984051-9aefd262-62e2-4d0d-90c3-2f63899aa81f.png)

Left is the target image and right is the predicted image. Iam using supervised technique rather than self-supervised framework using temporal consistency and LIPS loss function.

Can you please suggest in your module "SpikingRecEVFlowNet" encoder and decoder framework what changes needs to be incorporated apart from input and output channels.
Requesting you kindly to help on this regard

**Comment by fedepare** [comment]
Hi @ChidanandKumarKS, 

We haven't tried using our architectures for event-based image reconstruction, so unfortunately we can't suggest what changes would need to be made for them to succeed in this task. 

What we can recommend though are the following repositories: [E2VID](https://github.com/uzh-rpg/rpg_e2vid), [E2VID+](https://github.com/TimoStoff/event_cnn_minimal), [Back to Event Basics](https://github.com/tudelft/ssl_e2vid), among others. You could have a look at their main architectures and build your own using our spiking submodules.
