### ISSUE TITLE
confused about the implement of gradient of arctan x

### ISSUE THREAD

**Issue by lbh666** [tudelft/event_flow#3]
https://github.com/tudelft/event_flow/blob/7d90c9dcbd989ded49c34d32b50796ecdd5fbb88/models/spiking_util.py#L42
The derivative of arctan x is 1/(1 + x**2), but in your code it's 1 / (1 + width * x.abs()) ** 2.Is there anything wrong?
I appreciate your quick response.

**Comment by fedepare** [comment]
The line of code in your comment corresponds to the SuperSpike surrogate gradient from Zenke et al. 2018.

The code that you are looking for is in the ArctanSpike class.

https://github.com/tudelft/event_flow/blob/7d90c9dcbd989ded49c34d32b50796ecdd5fbb88/models/spiking_util.py#L92
