### ISSUE TITLE
Confused about the  evaluation result of my trained model

### ISSUE THREAD

**Issue by dedewoov** [tudelft/event_flow#4]
I trained a spiking neural network with the command (python train_flow.py --configs/train_SNN.yml). Then, to test my trained model, I run the command (python eval_flow.py <model_name> --config configs/eval_MVSEC.yml), where for <model name> I use my own trained model ID.
However, the estimation results of my trained model are not as good as the pre-trained model. How do I reproduce the results of the pre-trained model?
my trained model:
![image](https://user-images.githubusercontent.com/117733205/203504259-4812a9c0-b8c5-493f-977b-f123086c4977.png)
pretrained model:
![image](https://user-images.githubusercontent.com/117733205/203504302-f9d4e7bc-3386-4d82-81b8-bf4dfb45eef9.png)

I appreciate your quick response.^.^

**Comment by Huizerd** [comment]
I recently trained a LIFFireNet exactly following the readme, and then evaluated it on MVSEC. I got an AEE of 0.898, which is in line with the pre-trained model. Make sure to use the link in the readme for the datasets: https://1drv.ms/u/s!Ah0kx0CRKrAZjx-EEIzfo8iqBDro?e=TIoxG9. If you changed some code and then got these results, then there must be something off in the code, as these numbers suggest the model isn't learning at all. Good luck!
