### ISSUE TITLE
About time-steps

### ISSUE THREAD

**Issue by NorthSummer** [tudelft/event_flow#5]
Hi, don't know if you are still there~ May I ask the applied time-steps of trained SNN, according to the code and paper, I found it to be one defaultly. Have you tried to add up the time-steps? Thanks!

**Comment by Huizerd** [comment]
No, we haven't tried, doing multiple timesteps with the same input makes sense for static tasks (e.g. classification without a temporal dimension, such as MNIST), but less so for streaming tasks, especially when the sensor has such a high temporal resolution
