### ISSUE TITLE
Inquiry Regarding GPU Usage and Parallel Computation

### ISSUE THREAD

**Issue by JamesYang110043** [tudelft/event_flow#8]
Dear authors,

It's me again. I'm curious about the GPU(s) you utilized for neural network training in your implementation.
And, could you provide experiment detail about the training time?
Additionally, did you consider employing multiple GPUs for parallel processing?

Thank you for your time and assistance.

**Comment by Huizerd** [comment]
Hi James,

I think we still used a 1080Ti for this project, but I don't remember the time it took to train. We didn't look at employing multiple GPUs.

Good luck with your project!
