### ISSUE TITLE
Why read h5 data using batch_size

### ISSUE THREAD

**Issue by CheungBH** [tudelft/event_flow#9]
Thanks for your work. I am running your code for training, and found something strange. 
https://github.com/tudelft/event_flow/blob/e81f9630a145da8c7e57b2cfd38cf6c0b47ac14f/dataloader/h5.py#L66
The code read the h5 file based on the batch-size configuration. Why is it?

**Comment by Huizerd** [comment]
Hi! This is because it loads a different file for every element in the batch. So for a larger batch size, it will have to open more files.
